[build]
  publish = "Final-YBTV-Studios/public"
  command = "cd Final-YBTV-Studios && hugo --gc --themesDir ./themes/"
  
[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_THEME = "YBTV-officialwebsite"
  HUGO_BASEURL = "/"
