[build]
  publish = "YBTV-website/public"
  command = "cd YBTV-website && hugo --gc --themesDir ./themes/"
  
[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"